In [42]:
import tensorflow as tf
import pandas as pd

In [43]:
from sklearn.datasets import load_breast_cancer

In [44]:
cancer = load_breast_cancer()
x = cancer.data
y = cancer.target

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,stratify=y,test_size=0.3)

In [46]:
pd.Series(y).value_counts(normalize = True)

1    0.627417
0    0.372583
dtype: float64

In [47]:
pd.Series(y_train).value_counts(normalize = True)

1    0.628141
0    0.371859
dtype: float64

In [48]:
x_train[:2]

array([[1.162e+01, 1.818e+01, 7.638e+01, 4.088e+02, 1.175e-01, 1.483e-01,
        1.020e-01, 5.564e-02, 1.957e-01, 7.255e-02, 4.101e-01, 1.740e+00,
        3.027e+00, 2.785e+01, 1.459e-02, 3.206e-02, 4.961e-02, 1.841e-02,
        1.807e-02, 5.217e-03, 1.336e+01, 2.540e+01, 8.814e+01, 5.281e+02,
        1.780e-01, 2.878e-01, 3.186e-01, 1.416e-01, 2.660e-01, 9.270e-02],
       [1.120e+01, 2.937e+01, 7.067e+01, 3.860e+02, 7.449e-02, 3.558e-02,
        0.000e+00, 0.000e+00, 1.060e-01, 5.502e-02, 3.141e-01, 3.896e+00,
        2.041e+00, 2.281e+01, 7.594e-03, 8.878e-03, 0.000e+00, 0.000e+00,
        1.989e-02, 1.773e-03, 1.192e+01, 3.830e+01, 7.519e+01, 4.396e+02,
        9.267e-02, 5.494e-02, 0.000e+00, 0.000e+00, 1.566e-01, 5.905e-02]])

In [49]:
x_train.shape,x_test.shape

((398, 30), (171, 30))

In [50]:
set(cancer.target)

{0, 1}

In [51]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [52]:
model = Sequential()
model.add(Dense(10, activation = "relu", input_shape=[x_train.shape[1],],name = "hidden_1"))
model.add(Dense(20, activation = "relu", name = "hidden_2"))
model.add(Dense(10, activation = "relu", name = "hidden_3"))
model.add(Dense(10, activation = "relu", name = "hidden_4"))
model.add(Dense(1, activation = 'sigmoid', name = "output_layer"))
model.summary() # 310 weights and bais

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1 (Dense)            (None, 10)                310       
                                                                 
 hidden_2 (Dense)            (None, 20)                220       
                                                                 
 hidden_3 (Dense)            (None, 10)                210       
                                                                 
 hidden_4 (Dense)            (None, 10)                110       
                                                                 
 output_layer (Dense)        (None, 1)                 11        
                                                                 
Total params: 861
Trainable params: 861
Non-trainable params: 0
_________________________________________________________________


In [53]:
model.weights

[<tf.Variable 'hidden_1/kernel:0' shape=(30, 10) dtype=float32, numpy=
 array([[-0.2654554 , -0.2845589 ,  0.06983432, -0.01551363,  0.30945903,
          0.07367212, -0.22178528,  0.1194675 , -0.38254067, -0.03263319],
        [ 0.1232394 , -0.35054553,  0.23518306, -0.24920703, -0.03082454,
         -0.03998458,  0.09907183, -0.15680854, -0.26576105, -0.3059242 ],
        [-0.30871952,  0.22389013,  0.36786878, -0.18094672,  0.2579348 ,
          0.2401936 ,  0.30312645, -0.13156506,  0.27262634, -0.1331386 ],
        [-0.19947559,  0.15718472, -0.2654748 , -0.14589988, -0.06317133,
          0.3509112 , -0.1234211 ,  0.12898582, -0.09858161, -0.08442178],
        [ 0.22744435, -0.21751754,  0.3855623 ,  0.34434736,  0.11384428,
          0.15603429,  0.01796937,  0.0718922 ,  0.3666638 ,  0.25741905],
        [-0.18072595,  0.02751243,  0.20277041, -0.05176511, -0.25712696,
          0.09937048,  0.27296698,  0.16641474,  0.13923031, -0.3287546 ],
        [ 0.01913422, -0.3328215 , 

In [54]:
model.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics =['accuracy'] )

In [55]:
#these is training the data 
# epochs is number of iteration or number of epochs is equal to number of completing  forward path 
history = model.fit(x_train,y_train,epochs = 100,validation_data = (x_test,y_test))

Epoch 1/100
13/13 [==============================] - 0s 11ms/step - loss: 674.3570 - accuracy: 0.5578 - val_loss: 0.6918 - val_accuracy: 0.6257
Epoch 2/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6910 - accuracy: 0.6281 - val_loss: 0.6899 - val_accuracy: 0.6257
Epoch 3/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6890 - accuracy: 0.6281 - val_loss: 0.6881 - val_accuracy: 0.6257
Epoch 4/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6872 - accuracy: 0.6281 - val_loss: 0.6863 - val_accuracy: 0.6257
Epoch 5/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6855 - accuracy: 0.6281 - val_loss: 0.6847 - val_accuracy: 0.6257
Epoch 6/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6839 - accuracy: 0.6281 - val_loss: 0.6832 - val_accuracy: 0.6257
Epoch 7/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6823 - accuracy: 0.6281 - val_loss: 0.6817 - val_accuracy: 0.6257
Epoch 8/10

Epoch 59/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6608 - accuracy: 0.6281 - val_loss: 0.6618 - val_accuracy: 0.6257
Epoch 60/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6607 - accuracy: 0.6281 - val_loss: 0.6618 - val_accuracy: 0.6257
Epoch 61/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6607 - accuracy: 0.6281 - val_loss: 0.6617 - val_accuracy: 0.6257
Epoch 62/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6606 - accuracy: 0.6281 - val_loss: 0.6617 - val_accuracy: 0.6257
Epoch 63/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6606 - accuracy: 0.6281 - val_loss: 0.6616 - val_accuracy: 0.6257
Epoch 64/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6606 - accuracy: 0.6281 - val_loss: 0.6616 - val_accuracy: 0.6257
Epoch 65/100
13/13 [==============================] - 0s 3ms/step - loss: 0.6605 - accuracy: 0.6281 - val_loss: 0.6616 - val_accuracy: 0.6257
Epoch 

In [56]:
y_pred = model.predict(x_test)
y_pred

array([[0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],
       [0.6235288],


In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [58]:
y_test

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])